"""Added nullable fields (client and services)

Revision ID: 194405163dc4
Revises: 371dff1fd728
Create Date: 2025-11-22 18:45:18.807001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '194405163dc4'
down_revision: Union[str, Sequence[str], None] = '371dff1fd728'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'email',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('clients', 'phone',
               existing_type=sa.VARCHAR(length=11),
               nullable=True)
    op.alter_column('clients', 'address',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('services', 'cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('services', 'description',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('services', 'description',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('services', 'cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('clients', 'address',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('clients', 'phone',
               existing_type=sa.VARCHAR(length=11),
               nullable=False)
    op.alter_column('clients', 'email',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
