"""Separate User Profile from User Auth Credentials

Revision ID: 1f4d24fda509
Revises: 6da479e5284b
Create Date: 2026-01-22 17:29:56.235509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f4d24fda509'
down_revision: Union[str, Sequence[str], None] = '6da479e5284b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_credentials',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_user_id', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_credentials_id'), 'auth_credentials', ['id'], unique=False)
    op.create_index(op.f('ix_auth_credentials_user_id'), 'auth_credentials', ['user_id'], unique=False)
    op.drop_constraint(op.f('contracts_service_id_fkey'), 'contracts', type_='foreignkey')
    op.drop_constraint(op.f('contracts_client_id_fkey'), 'contracts', type_='foreignkey')
    op.create_foreign_key(None, 'contracts', 'clients', ['client_id'], ['id'])
    op.create_foreign_key(None, 'contracts', 'services', ['service_id'], ['id'])
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'contracts', type_='foreignkey')
    op.drop_constraint(None, 'contracts', type_='foreignkey')
    op.create_foreign_key(op.f('contracts_client_id_fkey'), 'contracts', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('contracts_service_id_fkey'), 'contracts', 'services', ['service_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_auth_credentials_user_id'), table_name='auth_credentials')
    op.drop_index(op.f('ix_auth_credentials_id'), table_name='auth_credentials')
    op.drop_table('auth_credentials')
    # ### end Alembic commands ###
