"""Added cascade relationships to tables that refeer to users

Revision ID: 3bed6bfe73af
Revises: d59d931775e1
Create Date: 2025-11-17 17:31:46.089200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bed6bfe73af'
down_revision: Union[str, Sequence[str], None] = 'd59d931775e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('clients_user_id_fkey'), 'clients', type_='foreignkey')
    op.create_foreign_key(None, 'clients', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('contracts_user_id_fkey'), 'contracts', type_='foreignkey')
    op.create_foreign_key(None, 'contracts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('services_user_id_fkey'), 'services', type_='foreignkey')
    op.create_foreign_key(None, 'services', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.create_foreign_key(op.f('services_user_id_fkey'), 'services', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'contracts', type_='foreignkey')
    op.create_foreign_key(op.f('contracts_user_id_fkey'), 'contracts', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.create_foreign_key(op.f('clients_user_id_fkey'), 'clients', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
