"""Added demo columns to users

Revision ID: a6994be6836d
Revises: 875c7991697a
Create Date: 2025-11-17 15:59:48.129652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6994be6836d'
down_revision: Union[str, Sequence[str], None] = '875c7991697a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_demo', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('demo_expiration', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'demo_expiration')
    op.drop_column('users', 'is_demo')
    # ### end Alembic commands ###
