"""Remove clients duplicate constraints

Revision ID: d59d931775e1
Revises: a6994be6836d
Create Date: 2025-11-17 16:41:04.873961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd59d931775e1'
down_revision: Union[str, Sequence[str], None] = 'a6994be6836d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('clients_email_key'), 'clients', type_='unique')
    op.drop_constraint(op.f('clients_phone_key'), 'clients', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('clients_phone_key'), 'clients', ['phone'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('clients_email_key'), 'clients', ['email'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
