"""Nullable Hashed Password and OAuth fields

Revision ID: e7a521b9e11d
Revises: 1f4d24fda509
Create Date: 2026-01-22 18:44:43.229320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7a521b9e11d'
down_revision: Union[str, Sequence[str], None] = '1f4d24fda509'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auth_credentials', 'provider',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('auth_credentials', 'provider_user_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('auth_credentials', 'hashed_password',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auth_credentials', 'hashed_password',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('auth_credentials', 'provider_user_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('auth_credentials', 'provider',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
